version: '3.8'

services:
  apipipeline-db:
    build:
      context: ./apipipeline-db
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./:usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - postgres
  
  postgres:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/data/db

volumes:
  pgdata: