version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/db

  apipipeline-db:
    build:
      context: ./apipipeline-db
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./apipipeline-db:/usr/src/app
    env_file:
      - ./apipipeline-db/.env
    depends_on:
      - postgres

  accounts-svc:
    build:
      context: ./services/accounts-svc
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    volumes:
      - ./services/accounts-svc:/usr/src/app
    ports:
      - 5001:3200
    env_file:
      - ./services/accounts-svc/.env
    depends_on:
      - redis
      - rabbitmq
      - postgres

volumes:
  pgdata: